调整指定 branch/tag 的方式等
1 直接在名称末尾用@符号指定 branch/tag，不再使用选项来指定。
- 不再为该使用 -b 还是 -B 选项感到困惑。
- 名称格式： package_name@variant。
- variant 先与 branch 匹配，未找到再与 tag 匹配。

2 发布使用的目的目录名由 package 改为 packages。
- 感觉这样好一些。

3 完善打印帮助信息。

diff --git a/scripts/jgb-install b/scripts/jgb-install
--- a/scripts/jgb-install
+++ b/scripts/jgb-install
@@ -4,8 +4,23 @@ set -e
 . jgb-helper
 jgb_arch=$(uname -p)
 
-while getopts  "p:" opt; do
+help()
+{
+    echo "[Usage] jgb-install [-f FILE] [-h] [-p <aarch64|x86_64>] <package>"
+    echo "-f FILE 指定包含包列表的 JSON 文件"
+    echo "-h display this help text, then exit"
+    echo "-p 选择目标架构"
+    exit 1
+} >&2
+
+while getopts  "f:hp:" opt; do
   case ${opt} in
+    f)
+      jgb_list_file=$OPTARG
+      ;;
+    h)
+      help
+      ;;
     p)
       jgb_arch=$OPTARG
       ;;
@@ -14,18 +29,48 @@ while getopts  "p:" opt; do
   esac
 done
 
-shift $((OPTIND - 1))
-pk=$1
-pk_file=${pk}.tar.gz
-for m in Debug Release
-do
-    pk_file_path=${JGB_BUILD_DIR}/package/$m/$jgb_arch/$pk/$pk_file
-    if [ ! -f $pk_file_path ] ; then
-      echo "not found: $pk"
-      exit 1
+install_package()
+{
+    local pk_full_name=$1
+    local pk=$(echo $pk_full_name | cut -d@ -f1)
+    local variant=$(echo $pk_full_name | cut -d@ -f2 -s)
+    local x_variant=
+    if [ -n "$variant" ] ; then
+      x_variant="_${variant}"
     fi
-    echo "extract: $pk"
-    dest_dir=${JGB_BUILD_DIR}/$m/$jgb_arch
-    mkdir -p $dest_dir
-    tar -C $dest_dir -xf $pk_file_path
-done
+    local pk_file=${pk}${x_variant}.tar.gz
+    for m in Debug Release
+    do
+        pk_file_path=${JGB_BUILD_DIR}/packages/$m/$jgb_arch/$pk/$pk_file
+        if [ ! -f $pk_file_path ] ; then
+          echo "not found: $pk_full_name"
+          exit 1
+        fi
+        echo "extract: $pk_full_name"
+        local dest_dir=${JGB_BUILD_DIR}/$m/$jgb_arch
+        mkdir -p $dest_dir
+        tar -C $dest_dir -xf $pk_file_path
+    done
+}
+
+if [ -n "$jgb_list_file" ] ; then
+  if [ -f "$jgb_list_file" ] ; then
+      x=0
+      while true;
+      do
+          pk_full_name=$(jq -r .packages[$x] $jgb_list_file)
+          if [ $pk_full_name != null ] ; then
+              install_package $pk_full_name
+              ((++x))
+          else
+              break
+          fi
+      done
+  fi
+fi
+
+shift $((OPTIND - 1))
+pk_full_name=$1
+if [ -n "$pk_full_name" ] ; then
+    install_package $pk_full_name
+fi
