FIXED
git branch 只是显示本地分支；
git branch -a 显示结果又太复杂，不仅仅只是分支名。

diff --git a/scripts/jgb-src b/scripts/jgb-src
--- a/scripts/jgb-src
+++ b/scripts/jgb-src
@@ -131,13 +131,10 @@ process_git_src()
   if [ -n "$variant" ] ; then
     #git fetch --tags
     #TODO：如果存在同名的 branch 和 tag，该如何处理？
-    if git branch | grep -q $variant ; then
-      git checkout $variant 2>/dev/null
-    elif git tag | grep -q $variant ; then
-      git checkout $variant 2>/dev/null
-    else
-      echo "not found: $variant"
-    fi
+    git checkout $variant 2>/dev/null || {
+        echo "variant not found: $variant"
+        exit 1
+    }
   fi
 }
 
