支持指定多个项目

diff --git a/scripts/jgb-push b/scripts/jgb-push
--- a/scripts/jgb-push
+++ b/scripts/jgb-push
@@ -36,6 +36,42 @@ help()
     exit 1
 } >&2
 
+push()
+{
+    pk_full_name=$1
+    pk=$(echo $pk_full_name | cut -d@ -f1)
+    variant=$(echo $pk_full_name | cut -d@ -f2 -s)
+    [ -n "$variant" ] && extra_opt="-V $variant"
+    for m in Debug Release;
+    do
+        src_dir=${JGB_BUILD_DIR}/local/packages/$m/${jgb_arch}/${pk}
+        dst_dir=${JGB_BUILD_DIR}/dist/packages/$m/${jgb_arch}/${pk}
+        package_file_name=${pk}${x_variant}-$(date +%Y%m%d).tar.gz
+        src_file_path=$src_dir/$package_file_name
+        dst_file_path=$dst_dir/$package_file_name
+        package_file_name_short=${pk}${x_variant}.tar.gz
+        if [ "$clean" == yes ] ; then
+            rm -vf $src_file_path
+            rm -vf $src_dir/$package_file_name_short
+        elif [ "$revert" == yes ] ; then
+            if [ -f $dst_file_path ] ; then
+                ln -vsf $package_file_name $dst_dir/$package_file_name_short
+            else
+                echo "not found: $pk_full_name [$dst_file_path]"
+                exit 1
+            fi
+        else
+            if [ ! -f $src_file_path ] ; then
+                echo "not found: $pk_full_name [$src_file_path]"
+                exit 1
+            fi
+            mkdir -p $dst_dir
+            /bin/cp -v $src_file_path $dst_dir
+            ln -vsf $package_file_name $dst_dir/$package_file_name_short
+        fi
+    done
+}
+
 while getopts  "cd:hp:r" opt; do
   case ${opt} in
     c)
@@ -59,12 +95,9 @@ while getopts  "cd:hp:r" opt; do
 done
 
 shift $((OPTIND - 1))
-pk_full_name=$1
-pk=$(echo $pk_full_name | cut -d@ -f1)
-variant=$(echo $pk_full_name | cut -d@ -f2 -s)
-[ -n "$variant" ] && extra_opt="-V $variant"
 
-if [ -z "$pk" ] ; then
+
+if [  $# -lt 1 ] ; then
   if [ "$clean" == yes ] && [ -n "$jgb_arch" ] ; then
     for m in Debug Release;
     do
@@ -82,31 +115,7 @@ if [ -z "$jgb_date" ] ; then
     jgb_date=$(date +%Y%m%d)
 fi
 
-for m in Debug Release;
+for pk_fn in "$@";
 do
-    src_dir=${JGB_BUILD_DIR}/local/packages/$m/${jgb_arch}/${pk}
-    dst_dir=${JGB_BUILD_DIR}/dist/packages/$m/${jgb_arch}/${pk}
-    package_file_name=${pk}${x_variant}-$(date +%Y%m%d).tar.gz
-    src_file_path=$src_dir/$package_file_name
-    dst_file_path=$dst_dir/$package_file_name
-    package_file_name_short=${pk}${x_variant}.tar.gz
-    if [ "$clean" == yes ] ; then
-        rm -vf $src_file_path
-        rm -vf $src_dir/$package_file_name_short
-    elif [ "$revert" == yes ] ; then
-        if [ -f $dst_file_path ] ; then
-            ln -vsf $package_file_name $dst_dir/$package_file_name_short
-        else
-            echo "not found: $pk_full_name [$dst_file_path]"
-            exit 1
-        fi
-    else
-        if [ ! -f $src_file_path ] ; then
-            echo "not found: $pk_full_name [$src_file_path]"
-            exit 1
-        fi
-        mkdir -p $dst_dir
-        /bin/cp -v $src_file_path $dst_dir
-        ln -vsf $package_file_name $dst_dir/$package_file_name_short
-    fi
+  push $pk_fn
 done
